### ISSUE TITLE
Rest api host not available anymore

### ISSUE THREAD

**Issue by madalinignisca** [KenWilliamson/LearningAngularJS_chapter6#1]
Hi Ken,

Could you help readers of your book to gain access to the rest api again?

http://nodeblog-micbuttoncloud.rhcloud.com/NodeBlog/*

This is not available anymore and the one in the book also is unavailable.

**Comment by KenWilliamson** [comment]
The old service has been removed.
The new service is: http://www.goblog.ulboralabs.com/GolangBlog
I changed all the code bases to with the new URL.
